#pragma once
/**
 * @file threecpp.h
 * @brief Main include file for ThreeCPP
 * 
 * @details
 * Include this file to get access to all ThreeCPP functionality.
 * Mirrors three.js namespace structure for API parity.
 * 
 * @usage
 * ```cpp
 * #include <threecpp/threecpp.h>
 * using namespace threecpp;
 * ```
 */

// Configuration (auto-generated by CMake)
#include "config.h"

// ===== Core Math Library =====
#include "vector2.h"
#include "vector3.h"
#include "vector4.h"
#include "matrix4.h"
#include "quaternion.h"
#include "euler.h"
#include "color.h"

// ===== Scene Graph =====
#include "object3d.h"
#include "scene.h"

// ===== Cameras =====
#include "camera.h"
#include "perspective_camera.h"
#include "orthographic_camera.h"

// ===== Geometry =====
#include "geometry.h"

// ===== Materials =====
#include "material.h"
#include "mesh_basic_material.h"
#include "mesh_phong_material.h"

// ===== Rendering =====
#include "mesh.h"
#include "light.h"
#include "ambient_light.h"
#include "directional_light.h"
#include "texture.h"
#include "renderer.h"

// ===== Graphics HAL =====
#include "graphics_device.h"

namespace threecpp {
    // Version information
    constexpr int VERSION_MAJOR = 0;
    constexpr int VERSION_MINOR = 1;
    constexpr int VERSION_PATCH = 0;
    
    inline std::string GetVersion() {
        return std::to_string(VERSION_MAJOR) + "." + 
               std::to_string(VERSION_MINOR) + "." + 
               std::to_string(VERSION_PATCH);
    }
}

#endif // THREECPP_H
